[project]
name = "cfutils"
version = "0.1.0"
description = "Shared utilities for Google Cloud Functions"
readme = "README.md"
authors = [
    { name = "Andy Eschbacher", email = "andyesch@protonmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "cloudevents>=1.11.0",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
