docker_image(
    name="docker",
    source="Dockerfile.activity_aggregator",
)

docker_image(
    name="docker0",
    source="Dockerfile.activity_bq_inserter",
)

docker_image(
    name="docker1",
    source="Dockerfile.activity_dispatcher",
)

docker_image(
    name="docker2",
    source="Dockerfile.apigateway",
)

# Python Cloud Function wrappers - will be configured in Phase 5
# For now, these are packaged via scripts/operations/package-functions.sh
# python_sources()
