# Docker Compose override for local hybrid development with real GCP resources
# Uses Terraform-created local GCP resources (BigQuery, Storage) + PubSub emulator
# Usage: docker-compose -f docker-compose.yml -f docker-compose.local.yml up

services:
  activity-dispatcher:
    environment:
      # For hybrid mode: use emulator project ID since PubSub still uses emulator
      - GCP_PROJECT_ID=local-dev
      - GCP_PUBSUB_TOPIC=desirelines_activity_events
      - PORT=8080
      # Use user credentials (mounted from host)
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/gcloud/application_default_credentials.json
    env_file:
      - .env
    volumes:
      # Mount your local gcloud config (Application Default Credentials)
      - ~/.config/gcloud:/app/.config/gcloud:ro

  activity-aggregator:
    environment:
      # Use real Terraform-created PubSub topics (no emulator)
      # Use user credentials (mounted from host)
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID_LIVE}
      # Override with live GCP project ID for AggregatorConfig
      - GCP_PROJECT_ID=${GCP_PROJECT_ID_LIVE}
      # Override with live GCP bucket name
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME_LIVE}
      # Strava credentials loaded from mounted volume at /etc/secrets/strava_auth.json
    volumes:
      - ./.env:/app/.env
      - ./functions/activity_aggregator.py:/app/main.py
      - ./packages/aggregator/src/aggregator:/app/aggregator
      # Mount your local gcloud config (Application Default Credentials)
      - ~/.config/gcloud:/app/.config/gcloud:ro

  activity-bq-inserter:
    environment:
      # Use real Terraform-created PubSub topics (no emulator)
      # Use user credentials (mounted from host)
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/gcloud/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID_LIVE}
      # Override with live GCP project ID and dataset for BQInserterConfig
      - GCP_PROJECT_ID=${GCP_PROJECT_ID_LIVE}
      - GCP_BIGQUERY_DATASET=desirelines
      # Strava credentials loaded from mounted volume at /etc/secrets/strava_auth.json
    volumes:
      - ./.env:/app/.env
      - ./functions/activity_bq_inserter.py:/app/main.py
      - ./packages/stravabqsync/src/stravabqsync:/app/stravabqsync
      # Mount your local gcloud config (Application Default Credentials)
      - ~/.config/gcloud:/app/.config/gcloud:ro

  # API Gateway - live Cloud Function integration (manual start only)
  api-gateway-live:
    profiles: ["frontend"]  # Only starts with --profile frontend
    build:
      context: .
      dockerfile: functions/Dockerfile.api_gateway
    ports:
      - "8084:8080"
    environment:
      - FUNCTION_TARGET=api_gateway
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME_LIVE}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.config/gcloud/application_default_credentials.json
      # Use user credentials for storage access
      - GCP_PROJECT_ID=${GCP_PROJECT_ID_LIVE}
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./functions/api_gateway.py:/app/main.py
      # Mount your local gcloud config (Application Default Credentials)
      - ~/.config/gcloud:/app/.config/gcloud:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Web App - live configuration (manual start only)
  web-live:
    profiles: ["frontend"]  # Only starts with --profile frontend
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      # Point to live API gateway (local Docker or deployed Cloud Function)
      - REACT_APP_API_URL=http://localhost:8084
      # Alternative: Use deployed Cloud Function directly
      # - REACT_APP_API_URL=https://us-central1-progressor-341702.cloudfunctions.net/api-gateway
      - REACT_APP_ENV=live
      - CHOKIDAR_USEPOLLING=true  # Hot reload in Docker
    volumes:
      - ./web/src:/app/src:ro
      - ./web/public:/app/public:ro
      # Exclude node_modules from bind mount for performance
      - /app/node_modules
    depends_on:
      - api-gateway-live

  # Keep emulator services - they're still useful!
  # pubsub-emulator and pubsub-bootstrap remain unchanged