"""Integration tests for the activity external-ID schema (V0010).

The ingested-from source column, the external-ID mapping and the cascading
foreign keys are what desirelines-owned activity IDs build on; these tests pin
them in place. IDs sit outside the local seed's range so they never collide.
"""

import pytest
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError

_ACTIVITY_ID = 9_100_001
_OTHER_ACTIVITY_ID = 9_100_002
_RENUMBERED_ID = 9_100_041


def _insert_activity(session, activity_id: int) -> None:
    session.execute(
        text("""
            INSERT INTO desirelines.activities
                (id, user_id, type, sport, start_date_local, year,
                 distance, moving_time, elapsed_time)
            VALUES (:id, 'identity-test', 'Ride', 'Ride', '2026-05-01 08:00:00', 2026,
                    1000, 100, 100)
        """),
        {"id": activity_id},
    )


def _insert_mapping(session, external_id: str, activity_id: int) -> None:
    session.execute(
        text("""
            INSERT INTO desirelines.activity_external_ids (source, external_id, activity_id)
            VALUES ('strava', :external_id, :activity_id)
        """),
        {"external_id": external_id, "activity_id": activity_id},
    )


def _count(session, table: str, activity_id: int) -> int:
    return session.execute(
        text(f"SELECT count(*) FROM desirelines.{table} WHERE activity_id = :id"),
        {"id": activity_id},
    ).scalar_one()


class TestActivityIdentitySchema:
    """V0010: the schema desirelines-owned activity IDs build on."""

    def test_the_schema_leaves_an_activitys_source_to_the_application(self, db_session):
        _insert_activity(db_session, _ACTIVITY_ID)

        source = db_session.execute(
            text("SELECT source FROM desirelines.activities WHERE id = :id"),
            {"id": _ACTIVITY_ID},
        ).scalar_one()
        assert source is None  # no DDL default; writers set it explicitly

    def test_activity_ids_come_from_an_identity_that_accepts_explicit_ids(
        self, db_session
    ):
        identity = db_session.execute(
            text("""
                SELECT attidentity FROM pg_attribute
                WHERE attrelid = 'desirelines.activities'::regclass AND attname = 'id'
            """)
        ).scalar_one()
        assert identity == "d"  # GENERATED BY DEFAULT: writers may still supply IDs

        _insert_activity(db_session, _ACTIVITY_ID)  # an explicit ID still inserts

    def test_renumbering_an_activity_carries_its_route_tags_and_mappings(
        self, db_session
    ):
        _insert_activity(db_session, _ACTIVITY_ID)
        db_session.execute(
            text("""
                INSERT INTO desirelines.activity_routes (activity_id, route)
                VALUES (:id, ST_Multi(ST_GeomFromText('LINESTRING(-30 0, -29 1)', 4326)))
            """),
            {"id": _ACTIVITY_ID},
        )
        db_session.execute(
            text("""
                INSERT INTO desirelines.activity_regions (activity_id, region_id)
                SELECT :id, id FROM desirelines.regions
                WHERE source = 'builtin' AND region_code = 'earth'
            """),
            {"id": _ACTIVITY_ID},
        )
        _insert_mapping(db_session, str(_ACTIVITY_ID), _ACTIVITY_ID)

        db_session.execute(
            text("UPDATE desirelines.activities SET id = :new WHERE id = :old"),
            {"new": _RENUMBERED_ID, "old": _ACTIVITY_ID},
        )

        for table in ("activity_routes", "activity_regions", "activity_external_ids"):
            assert _count(db_session, table, _RENUMBERED_ID) == 1, table
            assert _count(db_session, table, _ACTIVITY_ID) == 0, table
        external_id = db_session.execute(
            text("""
                SELECT external_id FROM desirelines.activity_external_ids
                WHERE activity_id = :id
            """),
            {"id": _RENUMBERED_ID},
        ).scalar_one()
        assert external_id == str(_ACTIVITY_ID)  # the platform ID survives renumbering

    def test_a_mapping_may_precede_its_activity_in_a_transaction(self, db_session):
        _insert_mapping(db_session, str(_ACTIVITY_ID), _ACTIVITY_ID)
        _insert_activity(db_session, _ACTIVITY_ID)

        # The deferred FK is checked now, as it would be at commit.
        db_session.execute(text("SET CONSTRAINTS ALL IMMEDIATE"))

    def test_a_mapping_without_its_activity_is_rejected_at_commit(self, db_session):
        _insert_mapping(db_session, "missing", _ACTIVITY_ID)

        with pytest.raises(IntegrityError):
            db_session.execute(text("SET CONSTRAINTS ALL IMMEDIATE"))

    def test_a_platform_id_maps_to_one_activity(self, db_session):
        _insert_activity(db_session, _ACTIVITY_ID)
        _insert_activity(db_session, _OTHER_ACTIVITY_ID)
        _insert_mapping(db_session, "shared", _ACTIVITY_ID)

        with pytest.raises(IntegrityError):
            _insert_mapping(db_session, "shared", _OTHER_ACTIVITY_ID)

    def test_tombstones_carry_their_external_id(self, db_session):
        db_session.execute(
            text("""
                INSERT INTO desirelines.deleted_activities (id, deletion_event_time)
                VALUES (:id, 1700000000)
            """),
            {"id": _ACTIVITY_ID},
        )

        row = db_session.execute(
            text("""
                SELECT source, external_id FROM desirelines.deleted_activities
                WHERE id = :id
            """),
            {"id": _ACTIVITY_ID},
        ).one()
        assert row.external_id == str(_ACTIVITY_ID)  # generated from id
        assert row.source is None  # no DDL default; writers set it explicitly
