-- Activity Identity: external-ID mapping
-- Migration: V0010
-- Concern: activities.id is the Strava activity ID, so every table and contract
--          is keyed by Strava. This adds what desirelines-owned IDs need: the
--          platform each activity was ingested from, a mapping from every
--          platform ID to the activity, and an identity on activities.id that
--          new IDs will come from.
--          Schema only: no ID changes here, and code keeps writing as before.
--
-- Foreign keys to activities.id now cascade on update, so a later migration can
-- renumber activities without breaking their routes, region tags and mappings.

-- =============================================================================
-- SET ROLE FOR CONSISTENT OWNERSHIP
-- =============================================================================

SET ROLE desirelines_ddl_grp;

-- =============================================================================
-- INGESTED-FROM PLATFORM
-- =============================================================================

-- No default: the application, not the schema, decides an activity's source.
-- Nullable for now so existing writers, which don't set it, keep working; every
-- existing row is a Strava activity. It becomes NOT NULL once writers set it.
ALTER TABLE desirelines.activities ADD COLUMN source TEXT;

UPDATE desirelines.activities SET source = 'strava';

COMMENT ON COLUMN desirelines.activities.source IS
  'Platform the activity was ingested from; the API''s source and sourceUrl '
  'link to the activity there.';

-- =============================================================================
-- EXTERNAL-ID MAPPING
-- =============================================================================

-- Every platform ID an activity is known by. The FK is deferrable so a writer can
-- insert the mapping before its activity in one transaction (duplicate-safe
-- inserts via ON CONFLICT on the mapping's primary key).
CREATE TABLE desirelines.activity_external_ids (
    source            TEXT        NOT NULL,
    external_id       TEXT        NOT NULL,
    activity_id       BIGINT      NOT NULL
        REFERENCES desirelines.activities(id)
        ON DELETE CASCADE ON UPDATE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    external_owner_id TEXT,
    linked_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (source, external_id)
);

CREATE INDEX idx_activity_external_ids_activity
    ON desirelines.activity_external_ids (activity_id);

COMMENT ON TABLE desirelines.activity_external_ids IS
  'Every platform ID an activity is known by: (source, external_id) resolves to '
  'the desirelines activity ID. external_owner_id is the athlete''s ID on that '
  'platform.';

-- Every existing activity is a Strava activity whose ID is its Strava ID.
INSERT INTO desirelines.activity_external_ids (source, external_id, activity_id, external_owner_id)
SELECT 'strava', id::text, id, user_id
FROM desirelines.activities;

-- =============================================================================
-- DESIRELINES ACTIVITY IDS
-- =============================================================================

-- desirelines-owned activity IDs come from this identity. BY DEFAULT, not ALWAYS:
-- writers still insert each activity's Strava ID explicitly, and a later
-- migration renumbers existing rows; both need to supply IDs. Unused until then.
-- Its sequence is owned by the column; default privileges (V0001) grant the DML
-- role USAGE, for writers that allocate an ID before inserting.
ALTER TABLE desirelines.activities
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

-- =============================================================================
-- CASCADING FOREIGN KEYS
-- =============================================================================

ALTER TABLE desirelines.activity_routes
    DROP CONSTRAINT activity_routes_activity_id_fkey,
    ADD CONSTRAINT activity_routes_activity_id_fkey
        FOREIGN KEY (activity_id) REFERENCES desirelines.activities(id)
        ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE desirelines.activity_regions
    DROP CONSTRAINT activity_regions_activity_id_fkey,
    ADD CONSTRAINT activity_regions_activity_id_fkey
        FOREIGN KEY (activity_id) REFERENCES desirelines.activities(id)
        ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================================
-- TOMBSTONES BY EXTERNAL ID
-- =============================================================================

-- A tombstone outlives its activity and its mappings, so a late CREATE can only be
-- matched by its platform ID. Tombstones are keyed by the Strava ID today, so
-- external_id is generated from id: always consistent, and the current tombstone
-- insert needs no change.
-- source follows the same rule as activities.source: no default, backfilled here,
-- NOT NULL once writers set it.
ALTER TABLE desirelines.deleted_activities
    ADD COLUMN source TEXT,
    ADD COLUMN external_id TEXT GENERATED ALWAYS AS (id::text) STORED;

UPDATE desirelines.deleted_activities SET source = 'strava';

CREATE UNIQUE INDEX deleted_activities_source_external_id_key
    ON desirelines.deleted_activities (source, external_id);

-- =============================================================================
-- GRANTS (for objects created in this migration)
-- =============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE desirelines.activity_external_ids TO desirelines_dml_grp;
GRANT SELECT ON TABLE desirelines.activity_external_ids TO desirelines_ro_grp;

-- =============================================================================
-- RESET ROLE
-- =============================================================================

-- Reset to original user so Flyway can update flyway_schema_history
RESET ROLE;
