/**
 * API Client for Activities
 *
 * API Contract for Empty/Missing Data:
 * ------------------------------------
 * The API follows a consistent pattern for handling missing data:
 *
 * | Scenario              | HTTP Status | Response Body                              |
 * |-----------------------|-------------|--------------------------------------------|
 * | Year/sport has data   | 200         | { timeseries: [...] } or { sports: [...] } |
 * | Year/sport NO data    | 200         | { timeseries: [] } or { sports: [] }       |
 * | Invalid year format   | 400         | { error: "Invalid year format" }           |
 * | Invalid sport         | 400         | { error: "Invalid sport: X" }              |
 * | Auth failure          | 401/403     | { error: "..." }                           |
 * | DB/Server error       | 500         | { error: "Internal server error" }         |
 *
 * Key principle: Empty data is NOT an error. The API returns 200 with empty
 * arrays/objects. 404 is only used for truly non-existent resources (wrong endpoint).
 *
 * Frontend handling:
 * - 200 responses: Display data (or empty state if arrays are empty)
 * - 400 responses: Show validation error to user
 * - 401/403: Redirect to login or show access denied
 * - 500: Show error message with retry option
 * - Cancelled requests: Silently ignore (return empty data)
 */

import client from "./client";
import { is404Error, throwApiError } from "./errors";

// Import generated types from Protobuf definitions
import type {
  Activity,
  ActivitySummary,
  ListActivitiesResponse as ActivityListResponse,
  ListActivitiesRequest as ActivityListFilter,
} from "../types/generated/activities";

import type {
  CumulativeMetricsEntry as MetricsEntry,
  SportMetrics as SportMetricsProto,
  YearMetadata,
  DailyActivity,
  DailySummary as DailySummaryResponse,
} from "../types/generated/sports_metrics";

// Re-export generated types for consumers
export type { Activity, ActivitySummary, ActivityListResponse, ActivityListFilter };
export type { MetricsEntry, YearMetadata, DailyActivity };

// Helper alias for the array type (frontend often uses just the array)
export type SportMetrics = MetricsEntry[];

// API Response - Matches protobuf sport config structure
// Note: This is NOT generated by Protobuf yet (defined in JSON schema)
export interface SportConfig {
  version: string;
  sport_categories: Record<
    string,
    {
      display_name: string; // "Cycling"
      strava_types: string[]; // ["Ride", "VirtualRide"]
      excluded_types: string[]; // ["EBikeRide"]
      primary_metric: string; // "distance_meters"
      metrics: string[]; // ["distance_meters", "time_minutes", ...]
      has_distance: boolean; // true for cycling/running, false for yoga
      has_elevation: boolean; // true for cycling/running, false for yoga
    }
  >;
}

// MULTI-SPORT API FUNCTIONS

/** Options for fetching sport metrics */
export interface FetchSportMetricsOptions {
  year: number;
  sport: string;
  from?: string; // YYYY-MM-DD - if provided with 'to', uses date range query
  to?: string; // YYYY-MM-DD - if provided with 'from', uses date range query
  signal?: AbortSignal;
}

export const fetchSportMetrics = async (
  yearOrOptions: number | FetchSportMetricsOptions,
  sport?: string,
  signal?: AbortSignal
): Promise<SportMetrics> => {
  // Support both old signature (year, sport, signal) and new options object
  const options: FetchSportMetricsOptions =
    typeof yearOrOptions === "number"
      ? { year: yearOrOptions, sport: sport!, signal }
      : yearOrOptions;

  let url = `/activities/${options.year}/metrics?sport=${options.sport}`;
  if (options.from && options.to) {
    url += `&from=${options.from}&to=${options.to}`;
  }

  try {
    const { data } = await client.get<SportMetricsProto>(url, {
      signal: options.signal,
    });
    return data.timeseries ?? [];
  } catch (err: unknown) {
    throwApiError(err, "fetchSportMetrics");
  }
};

export const fetchYearMetadata = async (
  year: number,
  signal?: AbortSignal
): Promise<YearMetadata> => {
  const url = `/activities/${year}/metadata`;

  try {
    const { data } = await client.get<YearMetadata>(url, {
      signal,
    });
    // Ensure arrays are never null for safe iteration
    return {
      ...data,
      sports: data.sports ?? [],
      totals: data.totals ?? {},
    };
  } catch (err: unknown) {
    throwApiError(err, "fetchYearMetadata");
  }
};

export const fetchSportConfig = async (signal?: AbortSignal): Promise<SportConfig> => {
  const url = `/sports/config`;

  try {
    const { data } = await client.get<SportConfig>(url, {
      signal,
    });
    return data;
  } catch (err: unknown) {
    throwApiError(err, "fetchSportConfig");
  }
};

/** Options for fetchDailySummary */
export interface FetchDailySummaryOptions {
  year: number;
  sport: string;
  signal?: AbortSignal;
  /** Start date (YYYY-MM-DD) for date-range queries */
  from?: string;
  /** End date (YYYY-MM-DD) for date-range queries */
  to?: string;
}

export const fetchDailySummary = async (
  options: FetchDailySummaryOptions
): Promise<Record<string, DailyActivity>> => {
  let url = `/activities/${options.year}/source?sport=${options.sport}`;
  if (options.from && options.to) {
    url += `&from=${options.from}&to=${options.to}`;
  }

  try {
    const { data } = await client.get<DailySummaryResponse>(url, {
      signal: options.signal,
    });
    return data.daily ?? {};
  } catch (err: unknown) {
    throwApiError(err, "fetchDailySummary");
  }
};

/**
 * Fetch a single activity by ID
 */
export const fetchActivity = async (id: number, signal?: AbortSignal): Promise<Activity | null> => {
  const url = `/activities/${id}`;

  try {
    const { data } = await client.get<Activity>(url, {
      signal,
    });
    return data;
  } catch (err: unknown) {
    // 404 means activity not found - return null, not an error
    if (is404Error(err)) {
      return null;
    }
    throwApiError(err, "fetchActivity");
  }
};

/**
 * Fetch paginated list of activities
 */
export const fetchActivities = async (
  filter: ActivityListFilter,
  signal?: AbortSignal
): Promise<ActivityListResponse> => {
  const params = new URLSearchParams();
  if (filter.from) params.set("from", filter.from);
  if (filter.to) params.set("to", filter.to);
  if (filter.sport) params.set("sport", filter.sport);
  if (filter.limit) params.set("limit", filter.limit.toString());
  if (filter.cursor) params.set("cursor", filter.cursor);

  const url = `/activities?${params.toString()}`;

  try {
    const { data } = await client.get<ActivityListResponse>(url, {
      signal,
    });
    return {
      activities: data.activities ?? [],
      nextCursor: data.nextCursor,
      hasMore: data.hasMore ?? false,
    };
  } catch (err: unknown) {
    throwApiError(err, "fetchActivities");
  }
};
