shell_sources()

python_sources(
    name="cloudevent_adapter",
    sources=["cloudevent_adapter.py"],
)

files(
    name="dockerfiles",
    sources=["Dockerfile.*"],
)

files(
    name="firebase_config",
    sources=["firebase-emulators.json"],
)
