name: Desirelines CI

on:
  push:
    paths-ignore:
      - '**/README.md'

env:
  GH_TOKEN: "foo"
  STRAVA_CLIENT_ID: 123
  STRAVA_REFRESH_TOKEN: "bar"
  STRAVA_CLIENT_SECRET: "baz"
  GCP_BUCKET_NAME: "gs://foo"
  GCP_SUMMARY_ACTIVITIES_PATH: "gs://bar"
  # Go environment variables for tests
  GCP_PROJECT_ID: "test-project"
  GCP_BIGQUERY_DATASET: "test_dataset"
  STRAVA_WEBHOOK_VERIFY_TOKEN: "test_verify_token"
  STRAVA_WEBHOOK_SUBSCRIPTION_ID: 12345
  GCP_PUBSUB_TOPIC_PATH: "projects/test-project/topics/test-topic"


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Desirelines App
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Python dependencies
      run: uv sync

    - name: Install Go dependencies
      run: cd packages/dispatcher && go mod download

    - name: Run Python tests
      run: uv run pytest packages/desirelines/tests/ --cov=./ --cov-report=xml && uv run pytest packages/stravabqsync/tests/ --cov=./ --cov-report=xml

    - name: Run Go tests
      run: cd packages/dispatcher && go test -v ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: andy-esch/desirelines
